"""Protocol types for presenter interfaces.

Views should annotate their presenter parameters with these protocols
instead of concrete controller classes, decoupling the view layer from
controller implementations.
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from .flashcard_controller import FlashcardState
from .test_controller import TestQuestionState
from .translation_controller import TranslationState
from .translation_sandbox_controller import SandboxState


class FlashcardPresenterProtocol(Protocol):
	"""Public interface consumed by FlashcardView."""

	def reset(self) -> None: ...
	def start(self, category: str) -> FlashcardState | None: ...
	def toggle(self) -> FlashcardState: ...
	def next(self) -> FlashcardState | None: ...
	def previous(self) -> FlashcardState: ...
	def current_state(self) -> FlashcardState: ...


class TranslationPresenterProtocol(Protocol):
	"""Public interface consumed by TranslationView."""

	def reset(self) -> None: ...
	def start(self, mode: str) -> TranslationState | None: ...
	def current_state(self) -> TranslationState | None: ...
	def next(self) -> TranslationState | None: ...
	def previous(self) -> TranslationState: ...
	def hint(self) -> str: ...
	def check_answer(self, user_input: str) -> tuple[bool, str]: ...
	def audio_path(self) -> str | None: ...
	def title_for_mode(self, mode: str) -> str: ...


class TestPresenterProtocol(Protocol):
	"""Public interface consumed by TestView, TestMenuScreen, TestRunnerScreen."""

	def reset(self) -> None: ...
	def total_questions(self) -> int: ...
	def answered_count(self) -> int: ...
	def has_active_prompt(self) -> bool: ...
	def current_state(self) -> TestQuestionState: ...
	def record_answer(self, answer: str, elapsed: float) -> None: ...
	def move_next(self) -> TestQuestionState: ...
	def move_previous(self) -> TestQuestionState: ...
	def can_move_next(self) -> bool: ...
	def can_move_previous(self) -> bool: ...
	def all_answered(self) -> bool: ...
	def summary(self) -> object: ...
	def responses(self) -> list: ...


class SandboxPresenterProtocol(Protocol):
	"""Public interface consumed by TranslationSandboxView."""

	def current_state(self) -> SandboxState: ...
	def toggle_mode(self) -> SandboxState: ...
	def set_mode(self, mode: str) -> SandboxState: ...
	def translate(self, text: str) -> SandboxState: ...
	def generate_audio(
		self,
		*,
		frequency: float | None = None,
		unit_duration_ms: int | None = None,
		volume: float | None = None,
	) -> SandboxState: ...
	def clear_audio(self) -> SandboxState: ...
	def save_audio_to_output(self) -> tuple[SandboxState, Path]: ...
	def save_audio_as(self, destination: Path) -> tuple[SandboxState, Path]: ...
	def update_volume(self, volume: float) -> SandboxState: ...
	def update_speed(self, unit_duration_ms: int) -> SandboxState: ...
	def update_pitch(self, frequency_hz: float) -> SandboxState: ...


__all__ = [
	"FlashcardPresenterProtocol",
	"SandboxPresenterProtocol",
	"TestPresenterProtocol",
	"TranslationPresenterProtocol",
]
